# Generated by Django 6.0.6 on 2026-10-02 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expenses',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(
                choices=[
                    ('food', 'Food'),
                    ('transport', 'Transport'),
                    ('shopping', 'Shopping'),
                    ('bills', 'Bills & Utilities'),
                    ('entertainment', 'Entertainment'),
                    ('health', 'Health'),
                    ('education', 'Education'),
                    ('games', 'Games'),
                    ('other', 'Other'),
                ],
                max_length=100,
            ),
        ),
    ]
